spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-active: 5000
        max-wait: -1
        min-idle: 1
        max-idle: 100
    timeout: 5000

